services:
  - type: web
    name: tmcp-auction
    runtime: node
    plan: free
    buildCommand: NODE_ENV=development npm install && npm run build:deploy
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AUCTIONEER_PASSWORD
        sync: false
      - key: JWT_EXPIRY
        value: 8h
